name: Download Sonntagsfrage
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create data_raw directory
        run: mkdir -p output/data/sonntagsfrage
      - name: Download Data
        run: >
          curl -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" -o
          output/data/sonntagsfrage/sonntagsfrage.csv
          https://api.apa.at/data/dossiers/datenpunkt_demokratie/sonntagsfrage/dossier_sonntagsfrage/nationalrat_details.csv
      - name: Save download time
        run: echo $(date '+%Y-%m-%d') > output/data/sonntagsfrage/sonntagsfrage_downloadtime.txt
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add -A
          git commit -am "Sonntagsfrage download at: $(date)"
          git push origin main
        env:
          REPO_KEY: '${{secrets.GITHUB_TOKEN}}'
          username: github-actions
